//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcalligator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChckIn
    {
        public int Id { get; set; }
        public Nullable<int> RoomNo { get; set; }
        public string GuestName { get; set; }
        public string CheckinDate { get; set; }
        public string PurposeOfVisit { get; set; }
        public Nullable<int> Deposit { get; set; }
        public Nullable<int> RoomRent { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
